name: Build/release

on:
  push:
    tags:        # Trigger the workflow only when a tag is pushed
      - 'v1.0.0'  #  Example: v1.0.0, v2.5.1

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write  # Required for creating releases

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    env:
      UPDATE_CHANNEL: "latest"  # Or your desired channel

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Add this step to fetch all tags
      - name: Fetch All Tags
        run: git fetch --force --tags

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build/release Electron app
        uses: heliomarpm/action-electron-builder@v2.1
        with:
          github_token: ${{ secrets.github_token }}
          release: true  # Ensure this is set to true
